-- Shortie Database Schema
-- V1: Create resources table
--
-- This migration creates the core resources table for storing
-- shortened URLs and file uploads.
--
-- IMPLEMENTATION NOTES:
-- - UUID primary key generated in application
-- - short_code has unique constraint and index for fast lookups
-- - state and expires_at indexed for expiration queries
-- - Using TIMESTAMPTZ for timezone-aware timestamps

-- Create enum types (Postgres)
-- Note: JPA will use VARCHAR, but these are here for documentation
-- CREATE TYPE resource_type AS ENUM ('URL', 'FILE');
-- CREATE TYPE resource_state AS ENUM ('ACTIVE', 'EXPIRED');

CREATE TABLE resources (
    -- Primary key: UUID generated by application
    id UUID PRIMARY KEY,
    
    -- Short code: unique identifier in URLs (e.g., /s/abc123)
    -- 16 chars max allows for future expansion
    short_code VARCHAR(16) NOT NULL UNIQUE,
    
    -- Resource type: URL or FILE
    type VARCHAR(10) NOT NULL CHECK (type IN ('URL', 'FILE')),
    
    -- For URL type: the original long URL
    original_url TEXT,
    
    -- For FILE type: path to stored file
    storage_path TEXT,
    
    -- For FILE type: original filename for download
    original_filename VARCHAR(255),
    
    -- Optional: maximum number of visits/downloads allowed
    max_visits INTEGER,
    
    -- Current visit/download count
    visit_count INTEGER NOT NULL DEFAULT 0,
    
    -- Optional: when the resource expires
    expires_at TIMESTAMPTZ,
    
    -- Current state: ACTIVE or EXPIRED
    state VARCHAR(10) NOT NULL DEFAULT 'ACTIVE' CHECK (state IN ('ACTIVE', 'EXPIRED')),
    
    -- Audit: when the resource was created
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    -- Constraints
    CONSTRAINT chk_url_required CHECK (
        (type = 'URL' AND original_url IS NOT NULL) OR
        (type = 'FILE' AND storage_path IS NOT NULL)
    )
);

-- Indexes for common queries
CREATE INDEX idx_resources_short_code ON resources(short_code);
CREATE INDEX idx_resources_state ON resources(state);
CREATE INDEX idx_resources_expires_at ON resources(expires_at) WHERE expires_at IS NOT NULL;
CREATE INDEX idx_resources_created_at ON resources(created_at);

-- Comments for documentation
COMMENT ON TABLE resources IS 'Stores shortened URLs and uploaded files';
COMMENT ON COLUMN resources.short_code IS 'Unique short identifier used in URLs';
COMMENT ON COLUMN resources.type IS 'Resource type: URL for shortened URLs, FILE for uploaded files';
COMMENT ON COLUMN resources.max_visits IS 'Optional limit on number of accesses';
COMMENT ON COLUMN resources.state IS 'ACTIVE = accessible, EXPIRED = no longer accessible';

